// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DGII.Data;

namespace DGII.Migrations
{
    [DbContext(typeof(DgiiDbContext))]
    partial class DgiiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrionTek.Data.Models.ComprobanteFiscal", b =>
                {
                    b.Property<int>("ComprobanteFiscalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("itbis18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ncf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rncCedula")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComprobanteFiscalId");

                    b.ToTable("ComprobantesFiscales");
                });

            modelBuilder.Entity("OrionTek.Data.Models.Contribuyente", b =>
                {
                    b.Property<int>("contribuyenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("estatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rncCedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("contribuyenteId");

                    b.ToTable("Contribuyentes");
                });
#pragma warning restore 612, 618
        }
    }
}
